<?xml version="1.0" encoding="utf-8"?>

<!-- ===================================================================== -->
<!-- WSDL voor alleen XSD variant op de bestaande "2009" XSD's, -->
<!-- deze XSD variant is gegenereerd conform de "2013" NEDU/EDSN standaard -->
<!-- en gemodellerd conform de bestaande "2009" XSD's. -->
<!-- Versie: 1.1 -->
<!-- Datum: 19/10/2012 --> 
<!-- ===================================================================== -->

<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:nl:edsn:service:fileupload:trans:1" xmlns:bm11="urn:nl:edsn:service:fileuploadnotification:env:1" xmlns:bm12="urn:nl:edsn:service:fileuploadacknowledgement:env:1" name="FileUpload" targetNamespace="urn:nl:edsn:service:fileupload:trans:1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sft="urn:edsn:edsn:data:soapfault:1:standard">
	<wsdl:documentation>version 1.1 dated 19/10/2012</wsdl:documentation>
	<wsdl:types>
		<xs:schema targetNamespace="urn:nl:edsn:service:fileupload:trans:1" elementFormDefault="qualified">
			<xs:import namespace="urn:nl:edsn:service:fileuploadnotification:env:1" schemaLocation="FileUploadNotification_1p0.xsd"/>
			<xs:import namespace="urn:nl:edsn:service:fileuploadacknowledgement:env:1" schemaLocation="FileUploadAcknowledgement_1p0.xsd"/>
			<xs:import namespace="urn:edsn:edsn:data:soapfault:1:standard" schemaLocation="SOAPFault_1p0.xsd"/>
		</xs:schema>
	</wsdl:types>
	<wsdl:message name="RequestMsg">
		<wsdl:part name="FileUploadNotificationEnvelope" element="bm11:FileUploadNotificationEnvelope"/>
	</wsdl:message>
	<wsdl:message name="PositiveResponseMsg">
		<wsdl:part name="FileUploadAcknowledgementEnvelope" element="bm12:FileUploadAcknowledgementEnvelope"/>
	</wsdl:message>
	<wsdl:message name="SOAPFault">
		<wsdl:part name="fault" element="sft:SOAPFault"/>
	</wsdl:message>
	<wsdl:portType name="FileUpload">
		<wsdl:operation name="FileUploadNotification">
			<wsdl:input message="tns:RequestMsg"/>
			<wsdl:output message="tns:PositiveResponseMsg"/>
			<wsdl:fault name="fault" message="tns:SOAPFault"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="FileUploadBinding" type="tns:FileUpload">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="FileUploadNotification">
			<soap:operation soapAction="FileUploadNotification" style="document"/>
			<wsdl:input>
				<soap:body use="literal" parts="FileUploadNotificationEnvelope"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="FileUploadAcknowledgementEnvelope"/>
			</wsdl:output>
			<wsdl:fault name="fault">
				<soap:fault name="fault" use="literal"/>
			</wsdl:fault>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="FileUploadService">
		<wsdl:port name="FileUploadPort" binding="tns:FileUploadBinding">
			<soap:address location="http://localhost:7001/b2b/bulk/upload/FileUpload"/>			
		</wsdl:port>
	</wsdl:service>
</wsdl:definitions>
